# fly.toml for Celery worker only
app = "alhaq-backend"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"  # ✅ Valid buildpack builder for Python

[env]
  PYTHONUNBUFFERED = "1"
  PORT = "8000"  # Fly requires a port even if Celery doesn't use HTTP

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[processes]
  celery = "uv run start_celery_only.py"
