app = "alhaq-backend"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  strategy = "rolling"

[processes]
  celery = "uv run celery -A core.tasks worker --loglevel=info"
