app = "alhaq-backend"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-buildpacks/python"]

[env]
  PORT = "8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512

[deploy]
  strategy = "rolling"

[processes]
  celery = "python start_celery_only.py 2"
