app = "alhaq-backend"
primary_region = "iad"

[build]
  # We skip buildpacks; Fly will use your image or system build
  image = "registry.fly.io/alhaq-backend:latest"

[env]
  PORT = "8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  strategy = "rolling"

[processes]
  celery = "uv run celery -A core.tasks worker --loglevel=info"
