"""initial_migration

Revision ID: 445ee9bfa76b
Revises: 
Create Date: 2026-03-08 00:53:59.027807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445ee9bfa76b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_payments', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_stats_id'), 'admin_stats', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'seller', 'admin', name='user_roles'), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('password_changed_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_order_updates', sa.Boolean(), nullable=True),
    sa.Column('email_payment_updates', sa.Boolean(), nullable=True),
    sa.Column('email_account_updates', sa.Boolean(), nullable=True),
    sa.Column('email_promotional_offers', sa.Boolean(), nullable=True),
    sa.Column('email_system_announcements', sa.Boolean(), nullable=True),
    sa.Column('sms_order_updates', sa.Boolean(), nullable=True),
    sa.Column('sms_payment_updates', sa.Boolean(), nullable=True),
    sa.Column('sms_account_updates', sa.Boolean(), nullable=True),
    sa.Column('push_order_updates', sa.Boolean(), nullable=True),
    sa.Column('push_payment_updates', sa.Boolean(), nullable=True),
    sa.Column('push_account_updates', sa.Boolean(), nullable=True),
    sa.Column('push_promotional_offers', sa.Boolean(), nullable=True),
    sa.Column('in_app_order_updates', sa.Boolean(), nullable=True),
    sa.Column('in_app_payment_updates', sa.Boolean(), nullable=True),
    sa.Column('in_app_account_updates', sa.Boolean(), nullable=True),
    sa.Column('in_app_promotional_offers', sa.Boolean(), nullable=True),
    sa.Column('in_app_system_announcements', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('order_confirmed', 'order_processing', 'order_shipped', 'order_delivered', 'order_cancelled', 'payment_successful', 'payment_failed', 'account_verified', 'password_changed', 'profile_updated', 'wishlist_item_back_in_stock', 'system_announcement', 'promotional_offer', 'car_approved', 'car_rejected', 'phone_approved', 'phone_rejected', 'inspection_scheduled', 'inspection_confirmed', 'property_acquired', 'agreement_completed', 'installment_paid', 'payment_reminder', 'installment_due', 'installment_defaulted', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='notification_priority'), nullable=True),
    sa.Column('channels', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('kyc_status', sa.Enum('pending', 'approved', 'rejected', name='kyc_status'), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('re_session_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('property_details', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'pending_acquisition', 'acquired', 'declined', name='re_session_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_re_session_requests_id'), 're_session_requests', ['id'], unique=False)
    op.create_table('seller_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('seller_type', sa.Enum('retailer', 'car_dealer', 'real_agent', 'phone_dealer', name='seller_type'), nullable=True),
    sa.Column('kyc_status', sa.Enum('pending', 'approved', 'rejected', name='seller_kyc_status'), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('available_balance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('pending_balance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_paid', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('payout_account_number', sa.String(length=20), nullable=True),
    sa.Column('payout_bank_code', sa.String(length=10), nullable=True),
    sa.Column('payout_bank_name', sa.String(length=100), nullable=True),
    sa.Column('payout_recipient_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_profiles_id'), 'seller_profiles', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_deposit_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('available', 'out_of_stock', name='car_listing_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_table('general_inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('automotive', 'property', 'phone', name='asset_category'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('inspection_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'completed', 'rejected', 'agreement_pending', 'agreement_accepted', name='gen_inspection_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_inspections_id'), 'general_inspections', ['id'], unique=False)
    op.create_table('phones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('specs', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_deposit_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('available', 'out_of_stock', name='phone_listing_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_id'), 'phones', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'out_of_stock', name='product_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('listing_type', sa.Enum('sale', 'rental', 'professional', name='listing_type'), nullable=True),
    sa.Column('status', sa.Enum('available', 'pending_inspection', 'property_inspected', 'awaiting_payment', 'reserved', 'sold', 'rented', 'under_financing', name='property_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('seller_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', name='payout_status'), nullable=True),
    sa.Column('transfer_reference', sa.String(length=100), nullable=True),
    sa.Column('paystack_transfer_id', sa.String(length=100), nullable=True),
    sa.Column('recipient_code', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_code', sa.String(length=10), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_reference')
    )
    op.create_index(op.f('ix_seller_payouts_id'), 'seller_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_seller_payouts_seller_id'), 'seller_payouts', ['seller_id'], unique=False)
    op.create_table('stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_buys', sa.Integer(), nullable=True),
    sa.Column('total_sells', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_stats_id'), 'stats', ['id'], unique=False)
    op.create_table('asset_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('phone_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_images_id'), 'asset_images', ['id'], unique=False)
    op.create_table('car_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('vin', sa.String(length=100), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('available', 'inspected', 'awaiting_payment', 'sold', 'reserved', name='unit_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_car_units_id'), 'car_units', ['id'], unique=False)
    op.create_table('general_agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.Enum('automotive', 'property', 'phone', name='asset_category'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deposit_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('remaining_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('plan_type', sa.Enum('structured', 'flexible', name='financing_plan_type'), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('monthly_installment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('next_due_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'pending_deposit', 'active', 'completed', 'defaulted', 'cancelled', name='gen_agreement_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['general_inspections.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_agreements_id'), 'general_agreements', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'shipped', 'delivered', 'cancelled', 'partially_shipped', 'partially_delivered', 'partially_cancelled', name='order_status'), nullable=True),
    sa.Column('delivery_address', sa.UUID(), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_initialized_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['delivery_address'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('phone_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_id', sa.UUID(), nullable=False),
    sa.Column('imei', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('battery_health', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('available', 'inspected', 'awaiting_payment', 'sold', 'reserved', name='phone_unit_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imei')
    )
    op.create_index(op.f('ix_phone_units_id'), 'phone_units', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'shipped', 'delivered', 'cancelled', name='order_item_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('agreement_id', sa.UUID(), nullable=True),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='payment_status'), nullable=True),
    sa.Column('payment_category', sa.Enum('order', 'asset_deposit', 'asset_installment', name='payment_category'), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('authorization_url', sa.Text(), nullable=True),
    sa.Column('access_code', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['general_agreements.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_phone_units_id'), table_name='phone_units')
    op.drop_table('phone_units')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_general_agreements_id'), table_name='general_agreements')
    op.drop_table('general_agreements')
    op.drop_index(op.f('ix_car_units_id'), table_name='car_units')
    op.drop_table('car_units')
    op.drop_index(op.f('ix_asset_images_id'), table_name='asset_images')
    op.drop_table('asset_images')
    op.drop_index(op.f('ix_stats_id'), table_name='stats')
    op.drop_table('stats')
    op.drop_index(op.f('ix_seller_payouts_seller_id'), table_name='seller_payouts')
    op.drop_index(op.f('ix_seller_payouts_id'), table_name='seller_payouts')
    op.drop_table('seller_payouts')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_phones_id'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_general_inspections_id'), table_name='general_inspections')
    op.drop_table('general_inspections')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_seller_profiles_id'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    op.drop_index(op.f('ix_re_session_requests_id'), table_name='re_session_requests')
    op.drop_table('re_session_requests')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_admin_stats_id'), table_name='admin_stats')
    op.drop_table('admin_stats')
    # ### end Alembic commands ###
