"""Add requested payment method

Revision ID: 68dcdae0b8b2
Revises: 47ac7bbf2daa
Create Date: 2026-03-28 08:29:15.018482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dcdae0b8b2'
down_revision = '47ac7bbf2daa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('requested_payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'requested_payment_method')
    # ### end Alembic commands ###
