"""describe your change clearly

Revision ID: 7e5fac565111
Revises: 09511ce9c956
Create Date: 2025-10-09 11:52:55.430640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e5fac565111'
down_revision = '09511ce9c956'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_activity_id'), table_name='login_activity')
    op.drop_table('login_activity')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_seller_payment_methods_id'), table_name='seller_payment_methods')
    op.drop_table('seller_payment_methods')
    op.drop_index(op.f('ix_user_security_id'), table_name='user_security')
    op.drop_table('user_security')
    op.drop_index(op.f('ix_customer_notification_preferences_id'), table_name='customer_notification_preferences')
    op.drop_table('customer_notification_preferences')
    # First create the ENUM type if it doesn't exist
    order_item_status_enum = sa.Enum('pending', 'processing', 'paid', 'shipped', 'delivered', 'cancelled', name='order_item_status')
    order_item_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Drop the default value first
    op.execute('ALTER TABLE order_items ALTER COLUMN status DROP DEFAULT')
    
    # Then alter the column with explicit casting
    op.execute('ALTER TABLE order_items ALTER COLUMN status TYPE order_item_status USING status::order_item_status')
    
    # Set the new default value
    op.execute("ALTER TABLE order_items ALTER COLUMN status SET DEFAULT 'pending'::order_item_status")
    op.alter_column('payments', 'seller_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'phone')
    op.alter_column('payments', 'seller_id',
               existing_type=sa.UUID(),
               nullable=False)
    # Convert back to VARCHAR
    op.execute('ALTER TABLE order_items ALTER COLUMN status TYPE VARCHAR(20) USING status::text')
    
    # Drop the ENUM type
    order_item_status_enum = sa.Enum('pending', 'processing', 'paid', 'shipped', 'delivered', 'cancelled', name='order_item_status')
    order_item_status_enum.drop(op.get_bind())
    op.create_table('customer_notification_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email_order_confirmations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_order_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_delivery_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_wishlist_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_price_drops', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_back_in_stock', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_promotional_offers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_newsletters', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_product_recommendations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_account_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_security_alerts', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_order_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_delivery_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_promotional_offers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sms_order_confirmations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sms_delivery_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sms_security_alerts', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['profiles.id'], name=op.f('customer_notification_preferences_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_notification_preferences_pkey'))
    )
    op.create_index(op.f('ix_customer_notification_preferences_id'), 'customer_notification_preferences', ['id'], unique=False)
    op.create_table('user_security',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('two_factor_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('backup_codes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('security_alerts', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recovery_questions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recovery_answers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_security_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_security_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_security_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_security_id'), 'user_security', ['id'], unique=False)
    op.create_table('seller_payment_methods',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bank_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('routing_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('method_type', postgresql.ENUM('bank_account', 'mobile_money', 'crypto', name='payment_method_types'), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verification_status', postgresql.ENUM('pending', 'verified', 'failed', name='verification_status'), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], name=op.f('seller_payment_methods_seller_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seller_payment_methods_pkey'))
    )
    op.create_index(op.f('ix_seller_payment_methods_id'), 'seller_payment_methods', ['id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('method_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('card_last_four', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('card_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('card_expiry_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_expiry_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payment_methods_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_methods_pkey'))
    )
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_table('login_activity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('login_successful', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('login_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('logout_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_activity_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('login_activity_pkey'))
    )
    op.create_index(op.f('ix_login_activity_id'), 'login_activity', ['id'], unique=False)
    # ### end Alembic commands ###
