"""add_dispute_table

Revision ID: 85bfbcbd9295
Revises: efcf1bd2ec0f
Create Date: 2026-03-30 12:54:32.465255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '85bfbcbd9295'
down_revision = 'efcf1bd2ec0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    migration_context = op.get_context()
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dispute_status_enum') THEN
                CREATE TYPE dispute_status_enum AS ENUM ('open', 'under_review', 'resolved', 'closed');
            END IF;
        END
        $$;
        """
    )
    dispute_status_enum = postgresql.ENUM(
        'open',
        'under_review',
        'resolved',
        'closed',
        name='dispute_status_enum',
        create_type=False,
    )
    if migration_context.as_sql:
        op.create_table('disputes',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('order_id', sa.UUID(), nullable=True),
            sa.Column('agreement_id', sa.UUID(), nullable=True),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('reason', sa.Text(), nullable=False),
            sa.Column('status', dispute_status_enum, nullable=True),
            sa.Column('resolution_notes', sa.Text(), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.ForeignKeyConstraint(['agreement_id'], ['general_agreements.id'], ),
            sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_disputes_agreement_id'), 'disputes', ['agreement_id'], unique=False)
        op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
        op.create_index(op.f('ix_disputes_order_id'), 'disputes', ['order_id'], unique=False)
        op.create_index(op.f('ix_disputes_user_id'), 'disputes', ['user_id'], unique=False)
        return

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'disputes' not in existing_tables:
        op.create_table('disputes',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('order_id', sa.UUID(), nullable=True),
            sa.Column('agreement_id', sa.UUID(), nullable=True),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('reason', sa.Text(), nullable=False),
            sa.Column('status', dispute_status_enum, nullable=True),
            sa.Column('resolution_notes', sa.Text(), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.ForeignKeyConstraint(['agreement_id'], ['general_agreements.id'], ),
            sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    existing_indexes = {idx["name"] for idx in inspector.get_indexes('disputes')} if 'disputes' in set(inspector.get_table_names()) else set()
    if op.f('ix_disputes_agreement_id') not in existing_indexes:
        op.create_index(op.f('ix_disputes_agreement_id'), 'disputes', ['agreement_id'], unique=False)
    if op.f('ix_disputes_id') not in existing_indexes:
        op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    if op.f('ix_disputes_order_id') not in existing_indexes:
        op.create_index(op.f('ix_disputes_order_id'), 'disputes', ['order_id'], unique=False)
    if op.f('ix_disputes_user_id') not in existing_indexes:
        op.create_index(op.f('ix_disputes_user_id'), 'disputes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_order_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_agreement_id'), table_name='disputes')
    op.drop_table('disputes')
    op.execute("DROP TYPE IF EXISTS dispute_status_enum")
    # ### end Alembic commands ###
