"""change_agreement_user_fk_to_users

Revision ID: b7113dd13645
Revises: f3b4c5d6e7f8
Create Date: 2026-03-24 09:34:11.809633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7113dd13645'
down_revision = 'f3b4c5d6e7f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('general_agreements_user_id_fkey'), 'general_agreements', type_='foreignkey')
    op.create_foreign_key(None, 'general_agreements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'general_agreements', type_='foreignkey')
    op.create_foreign_key(op.f('general_agreements_user_id_fkey'), 'general_agreements', 'profiles', ['user_id'], ['id'])
    # ### end Alembic commands ###
