"""add real estate session request fields

Revision ID: ee45bcc501bb
Revises: d4542ee5a74b
Create Date: 2026-03-13 07:36:41.996225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee45bcc501bb'
down_revision = 'd4542ee5a74b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_images', sa.Column('session_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'asset_images', 're_session_requests', ['session_request_id'], ['id'], ondelete='CASCADE')
    op.add_column('re_session_requests', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('re_session_requests', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('re_session_requests', sa.Column('proposed_price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.alter_column('re_session_requests', 'property_details',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('re_session_requests', 'property_details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('re_session_requests', 'proposed_price')
    op.drop_column('re_session_requests', 'description')
    op.drop_column('re_session_requests', 'title')
    op.drop_constraint(None, 'asset_images', type_='foreignkey')
    op.drop_column('asset_images', 'session_request_id')
    # ### end Alembic commands ###
