"""grace_period

Revision ID: efcf1bd2ec0f
Revises: 68dcdae0b8b2
Create Date: 2026-03-30 12:47:37.492064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcf1bd2ec0f'
down_revision = '68dcdae0b8b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_profiles', sa.Column('default_grace_period_days', sa.Integer(), server_default='3', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_profiles', 'default_grace_period_days')
    # ### end Alembic commands ###
